version: '3.0'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - '${PGPORT}:${PGPORT}'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  node:
    image: node:18.4.0-alpine

    volumes:
      - ./src:/usr/src/app/src
      
      - logs:/usr/logs

    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - '${PORT}:${PORT}'

networks:
  default:
    name: custom_network
    driver: bridge

volumes:
  app:
  logs:
  postgres-data:
  nodemodules:
